### ISSUE TITLE
JS2 Week 2 Feedback

### ISSUE THREAD

**Issue by orhantoy** [kfazinic/hyf-homework#2]
@kfazinic :v:

## Warmup array exercises / Doubling of number

Nice work 👍 

https://github.com/kfazinic/hyf-homework/blob/42dffa8702427fc443896ca19b773e3e4812f3c2/javascript/javascript2/week2/warmup.js#L4

Note: You could simplify the filtering like this:

```js
.filter((n) => n %2 !== 0)
```

## Warmup array exercises / Working with movies

- Exercise 1, 2, 3: ✅ Awesome, nice work 👍  You don't need `? true : false` as the checks themselves return a boolean (true/false). You can also access the properties like `movie.title` which is a bit nicer to read but your approach is identical, so no worries.
- Exercise 4: ✅ Looks good but using the ternary operator twice on a single line becomes a bit hard to read IMO. You could do a `if..else if..` which would use more lines but it would be easier to understand.
  A minor issue with your solution is that you're actually modifying the movie objects from `movies`. Ideally you should not be modifying that.
- Exercise 5: ✅ Nice!
- Exercise 6: ✅ Nice work here. The use of `reduce` could be a bit simpler but it's not a big deal 👍 
  https://github.com/kfazinic/hyf-homework/blob/42dffa8702427fc443896ca19b773e3e4812f3c2/javascript/javascript2/week2/warmup.js#L45-L52
- Execise 7: ✅ Interesting solution, nice work! I would've kept the splitting a bit simpler by just splitting on space. Overall the solution could be a bit simpler but it works 👍 

## hyfBay - get the okay'est products here - continued

Great work on this exercise! 🎉 
A few things could have been simplified a bit here but overall I'm really impressed. Keep up the good work.

I'm marking your assignment as approved ✅
Feel free to close this issue again unless you have questions.

**Comment by kfazinic** [comment]
Thank you for the feedback, @orhantoy! I applied the changes 🤠
