### ISSUE TITLE
DB Week 3 Feedback

### ISSUE THREAD

**Issue by orhantoy** [kfazinic/hyf-homework#3]
Hi @kfazinic :v:

Nice job!

- It is common to use `VARCHAR(255)` and as you have a value already close to 255 it would make sense to just use that. Not a big deal though.
  https://github.com/kfazinic/hyf-homework/blob/b71e31250e05d0a63abae5988af0ca2d1959bb12/databases/week3/meal_sharing.sql#L6
  https://github.com/kfazinic/hyf-homework/blob/b71e31250e05d0a63abae5988af0ca2d1959bb12/databases/week3/meal_sharing.sql#L8
- Your indentation and code style looks really good except for a few places where you're using a mix of tabs and spaces for indentation.
- All your Meal, Reservation and Review queries are correct, nice job here! 💪 
- All the Additional queries looks good as well, except for "Get meals that still has available reservations"
  https://github.com/kfazinic/hyf-homework/blob/b71e31250e05d0a63abae5988af0ca2d1959bb12/databases/week3/meal_sharing.sql#L270-L274
  You don't seem to handle that because multiple reservations can be made for a meal, that means that you have to aggregate/sum the number of guests for reservations for a meal and then filter out those that are booked up. Let me know if you need further assistance with this.

**Comment by orhantoy** [comment]
Hey! Have you had time to look into the feedback? Besides some minor things, I think you're only missing the query for "Get meals that still has available reservations".

**Comment by kfazinic** [comment]
Done! Thank you for the feedback :)
